services:
  customer-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customers
    ports:
      - "3307:3306"

  customerservice:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://customer-db:3306/customers
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update